SECRET_TOKEN:
DEVISE_SECRET:
DOMAIN_NAME:
GMAIL_USERNAME:
AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
FOG_PROVIDER:
FOG_DIRECTORY:

production:
  SECRET_TOKEN:
  DEVISE_SECRET:
  GMAIL_USERNAME:
  GMAIL_PASSWORD:
  DOMAIN_NAME:
  CLOUDFRONT_URL:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  FOG_PROVIDER:
  FOG_DIRECTORY:
  ROLLBAR_ACCESS_TOKEN:

